import React from "react";
import Layout from "@/layouts/Layout";
import Image from "next/image";
// import Link from "next/link";
import ProjectList from "../components/ProjectList";
// import "../styles/globals.scss";
import projects from "./projectsContent"; // Adjust the path as necessary

import styles from "./Home.module.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Home = () => {
  // export default function Home() {
  // const projects = [
  //   {
  //     id: "code-like-a-girl",
  //     title: "CLG",
  //     description: "Description of Project 1",
  //   },
  //   {
  //     id: "project2",
  //     title: "Project 2",
  //     description: "Description of Project 2",
  //   },
  // ];

  return (
    <Layout title="Home woo" className={styles.home}>
      <h1>boop</h1>
      <div>
        <h1>Oh my</h1>
        <Image
          src="/images/bird-initials@2x.png"
          alt="Bird"
          width={180}
          height={190}
          priority
        />
        <ol>
          <li>Get started by editing .</li>
          <li>Save and see your changes instantly.</li>
          <li>Hi Lara!</li>
          <li>Hello again, Lara!</li>
        </ol>
        <ProjectList projects={projects} />
        {/* </main> */}
      </div>
    </Layout>
  );
};

export default Home;
