import React from "react";
import Layout from "@/layouts/Layout";
import Image from "next/image";
import ProjectList from "../components/ProjectList";
import projects from "../content/projectsContent";

import styles from "./Home.module.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <Layout title="Home woo" className={styles.home}>
      <div>
        <h1 className={styles.intro}>
          Hi, saans is a sands-serif typeface designed by Martin Vácha and
          published through Displaay Type Foundry in 2023. It was created as a
          “neutral” addition to their type library. The family is available in
          six weights with matching italics, as well as mono and semi-mono
          styles.
        </h1>
        <Image
          src="/images/trio.svg"
          alt="Bird"
          width={180}
          height={190}
          priority
        />
        <ol>
          <li>Get started by editing .</li>
          <li>Save and see your changes instantly.</li>
          <li>Hi Lara!</li>
        </ol>
        <ProjectList projects={projects} />
      </div>
    </Layout>
  );
};

export default Home;
