// projectsData.js
const projects = {
  "code-like-a-girl": {
    title: "Code Like a Girl",
    description:
      "It's been a dream working at CLG. Maintain & update main site on Gatsby, design new pages for upcoming events (e.g., Virtual Engineering Summit).",
    thumbImage: "thumb-clg@2x.png",
    images: [
      "product-partners.jpg",
      "product-partners2.jpg",
      "product2.jpg",
      "product1.jpg",
      "website-home.jpg",
      "social-post.jpg",
      "social-post2.jpg",
      "website-tab.jpg",
      "website-how1.jpg",
      "website-jobs.jpg",
      "website-how2.jpg",
      "website-vcf.jpg",
      "website-vcf2.jpg",
    ],
    links: [
      { text: "Visit the website", url: "https://www.codelikeagirl.com" },
      {
        text: "I wrote a couple of coding courses too",
        url: "https://learnto.codelikeagirl.com/navigating-javascript",
      },
      {
        text: "Check out the GitHub repos",
        url: "https://www.codelikeagirl.com",
      },
    ],
  },
  "verve-super": {
    title: "Verve Super",
    description:
      "Working on Verve Super, was a freelance project focused on UX support and frontend development for a colleague-led UI project.",
    thumbImage: "thumb-verve@2x.png",
    images: [
      "verve-website-1.jpg",
      "verve-website-2.jpg",
      "verve-component-3.png",
      "verve-component-4.png",
      "verve-component-5.png",
      "verve-component-6.png",
      // "verve-website-3.jpg",
      "verve-website-5.jpg",
      "verve-component-2.png",
      "verve-component-1.png",
    ],
  },
  airtime: {
    title: "Airtime",
    description: "Detailed description of Airtime",
    thumbImage: "thumb-airtime@2x.png",
    images: [
      "airtime-web4@2x.jpg",
      "airtime-web1.png",
      "airtime-web2@2x.png",
      "airtime-initials.png",
      "airtime-web3@2x.jpg",
      "flying-ball1.png",
      "flying-ball2.png",
      "flying-ball3.png",
      "flying-ball4.png",
      "airtime-web5.jpg",
      "airtime-mock@2x.png",
    ],
  },
  "aime-mentoring": {
    title: "AIME Mentoring",
    description: "Detailed description of AIME",
    thumbImage: "thumb-aime@2x.png",
    images: [
      "aime-web1.jpg",
      "mock1.png",
      "mock2.png",
      "aime-sitemap.jpg",
      "landing-wf.jpg",
      "landing-site.jpg",
      "home1.jpg",
      "home2.jpg",
      "home3.jpg",
      "login.jpg",
    ],
  },
  bwf: {
    title: "Byron Writers Fest",
    description: "Detailed description of BWF",
    thumbImage: "thumb-bwf@2x.png",
    images: [
      "panel1.jpg ",
      "web-authors.jpg ",
      "web-stories.jpg ",
      "web-about2.jpg",
      "web-workshops.jpg ",
      "web-home.jpg ",
      "list.png",
      "web-about1.jpg ",
    ],
  },
  worthy: {
    title: "Worthy",
    description: "Detailed description of Worthy",
    thumbImage: "thumb-worthy@2x.png",
    images: [
      "create-event-a2.jpg ",
      "create-event-final.jpg ",
      "event-search-a.jpg ",
      "profile-wf.jpg ",
      "event-search-date.jpg ",
      "event-tile-a.jpg ",
      "event-tile-attending.jpg ",
      "profile-wf2.jpg ",
      "profile-z.jpg ",
      "RegisterCharity1.jpg ",
      "RegisterCharity2.jpg ",
      "RegisterCharityStep3.jpg ",
      "RegisterCharityStep3a.png ",
      "RegisterCharityStep4.jpg ",
      "review.jpg ",
      "z-empty-state.png ",
      "z-list-ui.png",
    ],
  },
};

export default projects;
